### ISSUE TITLE
Failes with error

### ISSUE THREAD

**Issue by GantMan** [kaushil24/Artificial-Eyeliner#2]
I get an OpenCV(3.4.4) error. Line 104 in the cv2.cvtColor(...) line "!_src.empty() is a function" when trying to run the default demo command.

Just like this one:
https://stackoverflow.com/questions/52676020/opencv-src-empty-in-function-cvtcolor-error

The video that gets outputted has the top 20% or so of the video, but not the bottom.

**Comment by kaushil24** [comment]
I believe there is some issue while reading the frame. Can you tell the dimensions of the frame (using `frame.shape` ) after the cv2.imread function.

**Comment by GantMan** [comment]
![Screenshot from 2019-12-19 12-18-58](https://user-images.githubusercontent.com/997157/71198681-f10fce00-2259-11ea-9d22-cf41d6f44a5f.png)

here's what happens when adding that frame.shape print. Seems you're right that the last frame dies.

**Comment by GantMan** [comment]
ok, so it still writes the file, and my jetson Nano was just showing it as broken.  I downloaded VLC and it seems to be working.  

I wrapped your code in a conditional to remove the error, but it actually worked.  Closing ticket.
